version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"  # RabbitMQ port
      - "15672:15672"  # RabbitMQ management UI port

  celery-worker:
    build: .
    depends_on:
      - rabbitmq
    command: celery -A tasks worker --loglevel=info
    volumes:
      - .:/app  # Mount current directory into the container
    environment:
      - C_FORCE_ROOT=true  # Allow running Celery worker as root (for development)

  app:
    build: .
    volumes:
      - .:/app  # Mount current directory into the container
    command: python main.py  # Command to run your application
